# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n-aWEdyF2VlQvQq3rbes6tPiF-y7S1SB
"""

#------------------------------------------------------------ Libraries
import torch
import numpy as np
import matplotlib.pyplot as plt
import platform
import math
torch.manual_seed(42)

import torch.nn as nn
import torch.optim as optim
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

#------------------------------------------------------------ Ex.1

def polynomial(z, coeffs):
  return coeffs[0] + z * coeffs[1] + z**2 * coeffs[2] + z**3 * coeffs[3] + z**4 * coeffs[4]

def plot_polynomial(coeffs, z_range, color='b'):
  z_min, z_max = z_range
  z = np.linspace( z_min, z_max, 100 )
  plt.figure()
  plt.plot(z, [polynomial(i,coeffs) for i in z], color=color, label='Exact ploynomial')
  plt.xlabel('z')
  plt.ylabel('p(z)')
  plt.legend()
  plt.savefig("Ex1.pdf")

w = np.array( [ 0, -10, 1, -1, 0.01 ] )
_range = (-3,3)
plot_polynomial(w , _range)

#------------------------------------------------------------ Ex.2

def create_dataset(coeffs, z_range=(-1,1), sample_size=10, sigma=0.1, seed=42):
    random_state = np.random.RandomState(seed)
    z_min, z_max = z_range
    X = random_state.uniform(z_min, z_max, (sample_size))
    X = np.array([X**i for i in range(5)])
    y_hat = np.dot(coeffs,X)
    y = y_hat + random_state.normal(0.0, sigma, (sample_size))
    return X, y

#------------------------------------------------------------ Ex.3

z_range = (-3,3)
sigma = 0.5
train_sample_size = 500
train_seed = 0
eval_sample_size = 500
eval_seed = 1

X_train, y_train = create_dataset(w, z_range, sample_size=train_sample_size, sigma=sigma, seed=train_seed)
X_eval, y_eval = create_dataset(w, z_range, sample_size=eval_sample_size, sigma=sigma, seed=eval_seed)

#------------------------------------------------------------ Ex.4

def visualize_data(X, y, coeffs, z_range, title=''):
  mark_col = 'r'
  if title == 'Evaluation_data':
    mark_col = 'orange'
  z_min, z_max = z_range
  z = np.linspace( z_min, z_max, 100 )
  plt.figure()
  plt.title(title)
  plt.plot(z, [polynomial(i,coeffs) for i in z], color='b', label='Exact ploynomial')
  plt.scatter(X[1], y, color=mark_col, marker='o', label=title)
  plt.xlabel('z')
  plt.ylabel('$y = p(z) + \epsilon$')
  plt.legend()
  plt.savefig("Ex4_"+title+".pdf")

visualize_data(X_train, y_train, w, z_range, title='Training_data')
visualize_data(X_eval, y_eval, w, z_range, title='Evaluation_data')

#------------------------------------------------------------ Ex.5

DEVICE = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print("Device:")
print(DEVICE)

model = nn.Linear(5, 1, bias = False)
loss_fn = nn.MSELoss()
learning_rate = 0.001
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

#X_train = X_train.reshape(train_sample_size, 1)
y_train = y_train.reshape(train_sample_size, 1)
#X_eval = X_eval.reshape(eval_sample_size, 1)
y_eval = y_eval.reshape(eval_sample_size, 1)

X_train = torch.tensor(X_train.T, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_eval = torch.tensor(X_eval.T, dtype=torch.float32)
y_eval = torch.tensor(y_eval, dtype=torch.float32)

X_train = X_train.to(DEVICE)
y_train = y_train.to(DEVICE)
X_eval = X_eval.to(DEVICE)
y_eval = y_eval.to(DEVICE)
model = model.to(DEVICE)

print('---------\t Exercise 5 (Training):\n\n')
n_steps = 5000

train_loss_plot = []
eval_loss_plot = []
w_estimates = np.zeros((5,n_steps))

for step in range(n_steps):
    # *** Training ***
    model.train()

    optimizer.zero_grad()
    y_hat = model(X_train)
    loss_train = loss_fn(y_hat, y_train)
    train_loss_plot.append( loss_train.item() )

    if step % 200 == 0:
            print("Step:", step, "- Loss train:", loss_train.item())
    loss_train.backward()
    optimizer.step()
    w_estimates[0,step] = model.weight[0,0].item()
    w_estimates[1,step] = model.weight[0,1].item()
    w_estimates[2,step] = model.weight[0,2].item()
    w_estimates[3,step] = model.weight[0,3].item()
    w_estimates[4,step] = model.weight[0,4].item()

    # *** Evaluation ***
    model.eval()

    with torch.no_grad():
        y_hat_eval = model(X_eval)
        # Compute the loss
        loss_eval = loss_fn(y_hat_eval, y_eval)
        eval_loss_plot.append( loss_eval.item() )

        if step % 200 == 0:
            print("Step:", step, "- Loss eval:", loss_eval.item())

print("Training done, with an evaluation loss of {}".format(loss_eval.item()))
print("Final w:", model.weight, "Final b:\n", model.bias)

#------------------------------------------------------------ Ex.6

steps = np.arange(n_steps)
fig, ax = plt.subplots()
axins = inset_axes(ax, width="40%", height="40%", loc="right")

ax.plot(steps, train_loss_plot, color='b', label='Training loss')
ax.plot(steps, eval_loss_plot, color='orange', label='Evaluation loss')
ax.set_xlabel('Steps')
ax.set_ylabel('Loss')
ax.legend()
zoom_start = 1490
zoom_end = 1500
axins.plot(steps, train_loss_plot, color='b')
axins.plot(steps, eval_loss_plot, color='orange')
axins.set_xlim(zoom_start, zoom_end)
axins.set_ylim(3, 3.2)
plt.savefig("Ex6.pdf")

#------------------------------------------------------------ Ex.7

estimated_coeffs = [w_estimates[0,-1],w_estimates[1,-1],\
                    w_estimates[2,-1],w_estimates[3,-1],w_estimates[4,-1]]

z_range = (-4,4)
z_min, z_max = z_range
z = np.linspace( z_min, z_max, 100 )
plt.figure()
plt.title('Model coefficients vs. true coefficients')
plt.plot(z,[polynomial(i,w) for i in z], color='b', label='Exact ploynomial')
plt.scatter(z, [polynomial(i,estimated_coeffs) for i in z], color='green', marker='o', label='Model')
plt.axvline(x=-3, color='lightgrey', linestyle='--', label=f'Training region')
plt.axvline(x=3, color='lightgrey', linestyle='--')
plt.xlabel('z')
plt.ylabel('p(z)')
plt.legend()
plt.savefig("Ex7.pdf")

#------------------------------------------------------------ Ex.8

plt.figure()
plt.title('$w_0$')
plt.plot(steps,w_estimates[0,steps], label='estimation')
plt.axhline(y=w[0], color='red', linestyle='--', label='True value')
plt.xlabel('Steps')
plt.ylabel('$w_0$')
plt.legend()
plt.savefig("Ex8_w0.pdf")

plt.figure()
plt.title('$w_1$')
plt.plot(steps,w_estimates[1,steps], label='estimation')
plt.axhline(y=w[1], color='red', linestyle='--', label='True value')
plt.xlabel('Steps')
plt.ylabel('$w_1$')
plt.legend()
plt.savefig("Ex8_w1.pdf")

plt.figure()
plt.title('$w_2$')
plt.plot(steps,w_estimates[2,steps], label='estimation')
plt.axhline(y=w[2], color='red', linestyle='--', label='True value')
plt.xlabel('Steps')
plt.ylabel('$w_2$')
plt.legend()
plt.savefig("Ex8_w2.pdf")

plt.figure()
plt.title('$w_3$')
plt.plot(steps,w_estimates[3,steps], label='estimation')
plt.axhline(y=w[3], color='red', linestyle='--', label='True value')
plt.xlabel('Steps')
plt.ylabel('$w_3$')
plt.legend()
plt.savefig("Ex8_w3.pdf")

plt.figure()
plt.title('$w_4$')
plt.plot(steps,w_estimates[4,steps], label='estimation')
plt.axhline(y=w[4], color='red', linestyle='--', label='True value')
plt.xlabel('Steps')
plt.ylabel('$w_4$')
plt.legend()
plt.savefig("Ex8_w4.pdf")

#------------------------------------------------------------ Ex.9

z_range = (-3,3)
sigma = 0.5
train_sample_size = 10
train_seed = 0
eval_sample_size = 500
eval_seed = 1
X_train, y_train = create_dataset(w, z_range, sample_size=train_sample_size, sigma=sigma, seed=train_seed)
X_eval, y_eval = create_dataset(w, z_range, sample_size=eval_sample_size, sigma=sigma, seed=eval_seed)

model = nn.Linear(5, 1, bias = False)
loss_fn = nn.MSELoss()
learning_rate = 0.001
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

y_train = y_train.reshape(train_sample_size, 1)
y_eval = y_eval.reshape(eval_sample_size, 1)
X_train = torch.tensor(X_train.T, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_eval = torch.tensor(X_eval.T, dtype=torch.float32)
y_eval = torch.tensor(y_eval, dtype=torch.float32)
X_train = X_train.to(DEVICE)
y_train = y_train.to(DEVICE)
X_eval = X_eval.to(DEVICE)
y_eval = y_eval.to(DEVICE)
model = model.to(DEVICE)

print('---------\t Exercise 9 (Training):\n\n')
n_steps = 5000

train_loss_plot = []
eval_loss_plot = []
w_estimates = np.zeros((5,n_steps))

for step in range(n_steps):
    # *** Training ***
    model.train()

    optimizer.zero_grad()
    y_hat = model(X_train)
    loss_train = loss_fn(y_hat, y_train)
    train_loss_plot.append( loss_train.item() )

    if step % 200 == 0:
            print("Step:", step, "- Loss train:", loss_train.item())
    loss_train.backward()
    optimizer.step()
    w_estimates[0,step] = model.weight[0,0].item()
    w_estimates[1,step] = model.weight[0,1].item()
    w_estimates[2,step] = model.weight[0,2].item()
    w_estimates[3,step] = model.weight[0,3].item()
    w_estimates[4,step] = model.weight[0,4].item()

    # *** Evaluation ***
    model.eval()

    with torch.no_grad():
        y_hat_eval = model(X_eval)
        # Compute the loss
        loss_eval = loss_fn(y_hat_eval, y_eval)
        eval_loss_plot.append( loss_eval.item() )

        if step % 200 == 0:
            print("Step:", step, "- Loss eval:", loss_eval.item())

print("Training done, with an evaluation loss of {}".format(loss_eval.item()))
print("Final w:", model.weight, "Final b:\n", model.bias)

steps = np.arange(n_steps)
plt.figure()
plt.plot(steps, train_loss_plot, color='b', label='Training loss')
plt.plot(steps, eval_loss_plot, color='orange', label='Evaluation loss')
plt.xlabel('Steps')
plt.ylabel('Loss')
plt.legend()
plt.savefig("Ex9_loss.pdf")

estimated_coeffs = [w_estimates[0,-1],w_estimates[1,-1],\
                    w_estimates[2,-1],w_estimates[3,-1],w_estimates[4,-1]]

z_range = (-4,4)
z_min, z_max = z_range
z = np.linspace( z_min, z_max, 100 )
plt.figure()
plt.title('Model coefficients vs. true coefficients')
plt.plot(z,[polynomial(i,w) for i in z], color='b', label='Exact ploynomial')
plt.scatter(z, [polynomial(i,estimated_coeffs) for i in z], color='green', marker='o', label='Model')
plt.axvline(x=-3, color='lightgrey', linestyle='--', label=f'Training region')
plt.axvline(x=3, color='lightgrey', linestyle='--')
plt.xlabel('z')
plt.ylabel('p(z)')
plt.legend()
plt.savefig("Ex9_prediction.pdf")

#------------------------------------------------------------ Ex.10

def f(x):
  return 5*math.sin(x)+3

def new_dataset(z_range=(-1,1), sample_size=10, sigma=0.1, seed=42):
    random_state = np.random.RandomState(seed)
    z_min, z_max = z_range
    x = random_state.uniform(z_min, z_max, (sample_size))
    y_hat = np.array([f(i) for i in x])
    y = y_hat + random_state.normal(0.0, sigma, (sample_size))

    return x, y

#----------------------- point a)
a = 0.01
x_range = (-a,a)
x_min, x_max = x_range
x = np.linspace( x_min, x_max, 100 )
plt.figure()
plt.plot(x, [f(i) for i in x], color='b', label='Exact function')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.savefig("Ex10a_exact.pdf")

#----- create datasets
sigma = 0.005
train_sample_size = 500
train_seed = 0
eval_sample_size = 500
eval_seed = 1
X_train, y_train = new_dataset( x_range, sample_size=train_sample_size, sigma=sigma, seed=train_seed)
X_eval, y_eval = new_dataset( x_range, sample_size=eval_sample_size, sigma=sigma, seed=eval_seed)

plt.figure()
plt.title('noisy data')
plt.plot(x, [f(i) for i in x], color='b', label='Exact function')
plt.scatter(X_train, y_train, color='r', marker='o', label='train data')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.savefig("Ex10a_noisy.pdf")

#------ reshape and prepare data
X_train = X_train.reshape(train_sample_size, 1)
y_train = y_train.reshape(train_sample_size, 1)
X_eval = X_eval.reshape(eval_sample_size, 1)
y_eval = y_eval.reshape(eval_sample_size, 1)

X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_eval = torch.tensor(X_eval, dtype=torch.float32)
y_eval = torch.tensor(y_eval, dtype=torch.float32)

X_train = X_train.to(DEVICE)
y_train = y_train.to(DEVICE)
X_eval = X_eval.to(DEVICE)
y_eval = y_eval.to(DEVICE)
model = model.to(DEVICE)

#------ model parameters
model = nn.Linear(1, 1)
loss_fn = nn.MSELoss()
learning_rate = 0.005
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

#------ training
print('---------\t Exercise 10.a (Training):\n\n')
n_steps = 5000

train_loss_plot = []
eval_loss_plot = []

for step in range(n_steps):
    # *** Training ***
    model.train()

    optimizer.zero_grad()
    y_hat = model(X_train)
    loss_train = loss_fn(y_hat, y_train)
    train_loss_plot.append( loss_train.item() )

    if step % 200 == 0:
            print("Step:", step, "- Loss train:", loss_train.item())
    loss_train.backward()
    optimizer.step()

    # *** Evaluation ***
    model.eval()

    with torch.no_grad():
        y_hat_eval = model(X_eval)
        # Compute the loss
        loss_eval = loss_fn(y_hat_eval, y_eval)
        eval_loss_plot.append( loss_eval.item() )

        if step % 200 == 0:
            print("Step:", step, "- Loss eval:", loss_eval.item())

print("Training done, with an evaluation loss of {}".format(loss_eval.item()))
print("Final w:", model.weight, "Final b:\n", model.bias)

#------ plot loss
steps = np.arange(n_steps)
plt.figure()
plt.plot(steps, train_loss_plot, color='b', label='Training loss')
plt.plot(steps, eval_loss_plot, color='orange', label='Evaluation loss')
plt.xlabel('Steps')
plt.ylabel('Loss')
plt.legend()
plt.savefig("Ex10a_loss.pdf")

#----------------------- point b)

a = 5
x_range = (-a,a)
x_min, x_max = x_range
x = np.linspace( x_min, x_max, 100 )
plt.figure()
plt.plot(x, [f(i) for i in x], color='b', label='Exact function')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.savefig("Ex10b_exact.pdf")

sigma = 0.5
train_sample_size = 500
train_seed = 0
eval_sample_size = 500
eval_seed = 1
X_train, y_train = new_dataset( x_range, sample_size=train_sample_size, sigma=sigma, seed=train_seed)
X_eval, y_eval = new_dataset( x_range, sample_size=eval_sample_size, sigma=sigma, seed=eval_seed)

plt.figure()
plt.title('noisy data')
plt.plot(x, [f(i) for i in x], color='b', label='Exact function')
plt.scatter(X_train, y_train, color='r', marker='o', label='train data')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.savefig("Ex10b_noisy.pdf")

X_train = X_train.reshape(train_sample_size, 1)
y_train = y_train.reshape(train_sample_size, 1)
X_eval = X_eval.reshape(eval_sample_size, 1)
y_eval = y_eval.reshape(eval_sample_size, 1)

X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_eval = torch.tensor(X_eval, dtype=torch.float32)
y_eval = torch.tensor(y_eval, dtype=torch.float32)

X_train = X_train.to(DEVICE)
y_train = y_train.to(DEVICE)
X_eval = X_eval.to(DEVICE)
y_eval = y_eval.to(DEVICE)
model = model.to(DEVICE)

model = nn.Linear(1, 1)
loss_fn = nn.MSELoss()
learning_rate = 0.0005
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

#----- training
print('---------\t Exercise 10.b (Training):\n\n')
n_steps = 5000
train_loss_plot = []
eval_loss_plot = []

for step in range(n_steps):
    # *** Training ***
    model.train()

    optimizer.zero_grad()
    y_hat = model(X_train)
    loss_train = loss_fn(y_hat, y_train)
    train_loss_plot.append( loss_train.item() )

    if step % 200 == 0:
            print("Step:", step, "- Loss train:", loss_train.item())
    loss_train.backward()
    optimizer.step()

    # *** Evaluation ***
    model.eval()

    with torch.no_grad():
        y_hat_eval = model(X_eval)
        # Compute the loss
        loss_eval = loss_fn(y_hat_eval, y_eval)
        eval_loss_plot.append( loss_eval.item() )

        if step % 200 == 0:
            print("Step:", step, "- Loss eval:", loss_eval.item())

print("Training done, with an evaluation loss of {}".format(loss_eval.item()))
print("Final w:", model.weight, "Final b:\n", model.bias)

steps = np.arange(n_steps)

plt.figure()
plt.plot(steps, train_loss_plot, color='b', label='Training loss')
plt.plot(steps, eval_loss_plot, color='orange', label='Evaluation loss')
plt.xlabel('Steps')
plt.ylabel('Loss')
plt.legend()
plt.savefig("Ex10_loss.pdf")